name: Release on main

on:
  push:
    branches: [ main ]

jobs:
  test-and-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt
      - name: Run tests
        env:
          FLASK_ENV: testing
        run: |
          . venv/bin/activate
          cp config.test.env .env
          pytest tests/ -v
      - name: Create and push tag
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          MAJOR=${LATEST_TAG#v}; MAJOR=${MAJOR%%.*}
          MINOR=${LATEST_TAG#v${MAJOR}.}; MINOR=${MINOR%%.*}
          PATCH=${LATEST_TAG##*.}
          NEW_TAG=v${MAJOR}.${MINOR}.$((PATCH+1))
          echo "Tagging ${NEW_TAG}"
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git tag -a ${NEW_TAG} -m "CI release ${NEW_TAG}"
          git push origin ${NEW_TAG}
